name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      working-directory: src/Utilities.Mongo
      run: dotnet restore
    - name: Build
      working-directory: src/Utilities.Mongo
      run: dotnet build --no-restore
    - name: Test
      working-directory: tests/Utilities.Mongo.UnitTests
      run: dotnet test --no-build --verbosity normal